// DO NOT MODIFY
// Automatically generated by Arkana (https://github.com/rogerluan/arkana)

plugins {
    id("kotlin")
}

kotlin {
    jvmToolchain(11)
}

tasks.test {
    useJUnitPlatform()
}

dependencies {
    testImplementation(kotlin("test"))
}
